/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package memoria;


/**
 *
 * @author 59399
 */
public class JFmemoria extends javax.swing.JFrame {
    int[] numeros=new int[16];
    int posicion,aleatorio,contador,abiertas,poscision,posicion2,intentos;
    int cartas=1;
    int valor1=10;
    int valor2=10;

    /**
     * Creates new form JFmemoria
     */
    public JFmemoria() {
        
        initComponents();
        while (contador<=14)
        {
            aleatorio=(int)(Math.random()*15 );
            if (numeros[aleatorio]==0)
            {
                numeros[aleatorio]=cartas;
                contador+=1;
                cartas+=1;
                if (cartas>7)
                {
                    cartas=0;
                }
            }
            
        }
        
        for (posicion=0;posicion<=15;posicion++)
        {
            System.out.print(numeros[posicion]);
        }
                    System.out.println();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnReset = new javax.swing.JButton();
        btm1 = new javax.swing.JButton();
        btm5 = new javax.swing.JButton();
        btm9 = new javax.swing.JButton();
        btm2 = new javax.swing.JButton();
        btm6 = new javax.swing.JButton();
        btm10 = new javax.swing.JButton();
        btm3 = new javax.swing.JButton();
        btm7 = new javax.swing.JButton();
        btm11 = new javax.swing.JButton();
        btm4 = new javax.swing.JButton();
        btm8 = new javax.swing.JButton();
        btm12 = new javax.swing.JButton();
        btm13 = new javax.swing.JButton();
        btm14 = new javax.swing.JButton();
        btm15 = new javax.swing.JButton();
        btm16 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        lblIntentos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        btnReset.setText("RESET");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });
        getContentPane().add(btnReset);
        btnReset.setBounds(10, 11, 110, 23);

        btm1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm1ActionPerformed(evt);
            }
        });
        getContentPane().add(btm1);
        btm1.setBounds(200, 20, 80, 90);

        btm5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm5ActionPerformed(evt);
            }
        });
        getContentPane().add(btm5);
        btm5.setBounds(200, 120, 80, 90);

        btm9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm9ActionPerformed(evt);
            }
        });
        getContentPane().add(btm9);
        btm9.setBounds(200, 220, 80, 100);

        btm2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm2ActionPerformed(evt);
            }
        });
        getContentPane().add(btm2);
        btm2.setBounds(290, 20, 80, 90);

        btm6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm6ActionPerformed(evt);
            }
        });
        getContentPane().add(btm6);
        btm6.setBounds(290, 120, 80, 90);

        btm10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm10ActionPerformed(evt);
            }
        });
        getContentPane().add(btm10);
        btm10.setBounds(290, 220, 80, 100);

        btm3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm3ActionPerformed(evt);
            }
        });
        getContentPane().add(btm3);
        btm3.setBounds(390, 20, 80, 90);

        btm7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm7ActionPerformed(evt);
            }
        });
        getContentPane().add(btm7);
        btm7.setBounds(390, 120, 80, 90);

        btm11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm11ActionPerformed(evt);
            }
        });
        getContentPane().add(btm11);
        btm11.setBounds(390, 220, 80, 100);

        btm4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm4ActionPerformed(evt);
            }
        });
        getContentPane().add(btm4);
        btm4.setBounds(490, 20, 80, 90);

        btm8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm8ActionPerformed(evt);
            }
        });
        getContentPane().add(btm8);
        btm8.setBounds(490, 120, 80, 90);

        btm12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm12ActionPerformed(evt);
            }
        });
        getContentPane().add(btm12);
        btm12.setBounds(490, 220, 80, 100);

        btm13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm13ActionPerformed(evt);
            }
        });
        getContentPane().add(btm13);
        btm13.setBounds(200, 340, 80, 100);

        btm14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm14ActionPerformed(evt);
            }
        });
        getContentPane().add(btm14);
        btm14.setBounds(290, 340, 80, 100);

        btm15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm15ActionPerformed(evt);
            }
        });
        getContentPane().add(btm15);
        btm15.setBounds(390, 340, 80, 100);

        btm16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btm16ActionPerformed(evt);
            }
        });
        getContentPane().add(btm16);
        btm16.setBounds(490, 340, 80, 100);

        jTextField1.setText("INTENTOS");
        getContentPane().add(jTextField1);
        jTextField1.setBounds(20, 80, 70, 30);
        getContentPane().add(lblIntentos);
        lblIntentos.setBounds(20, 120, 90, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btm1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm1ActionPerformed
    
    abiertas+=1;
    
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm1.setText(String.valueOf(numeros[0]));
        btm1.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[0];
        posicion=1;
        }
        else
        {
            valor2=numeros[0];
            posicion2=1;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
        
    }//GEN-LAST:event_btm1ActionPerformed

    private void btm2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm2ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm2.setText(String.valueOf(numeros[1]));
        btm2.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[1];
        posicion=2;
        }
        else
        {
            valor2=numeros[1];
            posicion2=2;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
     
    }//GEN-LAST:event_btm2ActionPerformed

    private void btm3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm3ActionPerformed
    
        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm3.setText(String.valueOf(numeros[2]));
        btm3.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[2];
        posicion=3;
        }
        else
        {
            valor2=numeros[2];
            posicion2=3;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
     // TODO add your handling code here:
    }//GEN-LAST:event_btm3ActionPerformed

    private void btm4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm4ActionPerformed

    
        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm4.setText(String.valueOf(numeros[3]));
        btm4.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[3];
        posicion=4;
        }
        else
        {
            valor2=numeros[3];
            posicion2=4;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        

    }//GEN-LAST:event_btm4ActionPerformed

    private void btm5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm5ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    { 
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm5.setText(String.valueOf(numeros[4]));
        btm5.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[4];
        posicion=5;
        }
        else
        {
            valor2=numeros[4];
            posicion2=5;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
     
    }//GEN-LAST:event_btm5ActionPerformed

    private void btm6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm6ActionPerformed

    
        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm6.setText(String.valueOf(numeros[5]));
        btm6.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[5];
        posicion=6;
        }
        else
        {
            valor2=numeros[5];
            posicion2=6;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
        
    }//GEN-LAST:event_btm6ActionPerformed

    private void btm7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm7ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm7.setText(String.valueOf(numeros[6]));
        btm7.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[6];
        posicion=7;
        }
        else
        {
            valor2=numeros[6];
            posicion2=7;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
      
    }//GEN-LAST:event_btm7ActionPerformed

    private void btm8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm8ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm8.setText(String.valueOf(numeros[7]));
        btm8.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[7];
        posicion=8;
        }
        else
        {
            valor2=numeros[7];
            posicion2=8;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
     
    }//GEN-LAST:event_btm8ActionPerformed

    private void btm9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm9ActionPerformed

    
        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm9.setText(String.valueOf(numeros[8]));
        btm9.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[8];
        posicion=9;
        }
        else
        {
            valor2=numeros[8];
            posicion2=9;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        

    }//GEN-LAST:event_btm9ActionPerformed

    private void btm10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm10ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm10.setText(String.valueOf(numeros[9]));
        btm10.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[9];
        posicion=10;
        }
        else
        {
            valor2=numeros[9];
            posicion2=10;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
     
    }//GEN-LAST:event_btm10ActionPerformed

    private void btm11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm11ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm11.setText(String.valueOf(numeros[10]));
        btm11.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[10];
        posicion=11;
        }
        else
        {
            valor2=numeros[10];
            posicion2=11;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
      
    }//GEN-LAST:event_btm11ActionPerformed

    private void btm12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm12ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm12.setText(String.valueOf(numeros[11]));
        btm12.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[11];
        posicion=12;
        }
        else
        {
            valor2=numeros[11];
            posicion2=12;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
     
    }//GEN-LAST:event_btm12ActionPerformed

    private void btm13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm13ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm13.setText(String.valueOf(numeros[12]));
        btm13.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[12];
        posicion=13;
        }
        else
        {
            valor2=numeros[12];
            posicion2=13;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
       
    }//GEN-LAST:event_btm13ActionPerformed

    private void btm14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm14ActionPerformed

    
        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm14.setText(String.valueOf(numeros[13]));
        btm14.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[13];
        posicion=14;
        }
        else
        {
            valor2=numeros[13];
            posicion2=14;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
     
    }//GEN-LAST:event_btm14ActionPerformed

    private void btm15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm15ActionPerformed

        abiertas+=1;
        
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
   
        btm15.setText(String.valueOf(numeros[14]));
        btm15.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[14];
        posicion=15;
        }
        else
        {
            valor2=numeros[14];
            posicion2=15;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
               case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
        
    }//GEN-LAST:event_btm15ActionPerformed

    private void btm16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btm16ActionPerformed

        abiertas+=1;
        
   
    
    if (abiertas<=2)
    {
        intentos+=1;
        lblIntentos.setText(String.valueOf(intentos));
        btm16.setText(String.valueOf(numeros[15]));
        btm16.setEnabled(false);
        if (valor1==10)
        {
        valor1=numeros[15];
        posicion=16;
        }
        else
        {
            valor2=numeros[15];
            posicion2=16;
        }
        
    }
    else 
        
        if (valor1!=valor2)
        {
            switch(posicion)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
                    
               
                    
            }
            
            switch(posicion2)
            {
                case 1 : btm1.setText(String.valueOf(" "));
                         btm1.setEnabled(true);
                break;
                case 2 : btm2.setText(String.valueOf(" "));
                         btm2.setEnabled(true);
                break;
                case 3 : btm3.setText(String.valueOf(" "));
                         btm3.setEnabled(true);
                break;
                case 4 : btm4.setText(String.valueOf(" "));
                         btm4.setEnabled(true);
                break;
                case 5 : btm5.setText(String.valueOf(" "));
                         btm5.setEnabled(true);
                break;
                case 6 : btm6.setText(String.valueOf(" "));
                         btm6.setEnabled(true);
                break;
                case 7 : btm7.setText(String.valueOf(" "));
                         btm7.setEnabled(true);
                break;
                case 8 : btm8.setText(String.valueOf(" "));
                         btm8.setEnabled(true);
                break;
                case 9 : btm9.setText(String.valueOf(" "));
                         btm9.setEnabled(true);
                break;
                case 10 : btm10.setText(String.valueOf(" "));
                          btm10.setEnabled(true);
                break;
                case 11 : btm11.setText(String.valueOf(" "));
                          btm11.setEnabled(true);
                break;
                case 12 : btm12.setText(String.valueOf(" "));
                          btm12.setEnabled(true);
                break;
                case 13 : btm13.setText(String.valueOf(" "));
                          btm13.setEnabled(true);
                break;
                case 14 : btm14.setText(String.valueOf(" "));
                          btm14.setEnabled(true);
                break;
                case 15 : btm15.setText(String.valueOf(" "));
                          btm15.setEnabled(true);
                break;
                case 16 : btm16.setText(String.valueOf(" "));
                          btm16.setEnabled(true);
                break;
            }
            
            valor1=10;
            valor2=10;
            abiertas=0;
        
        } 
        else if (valor1==valor2)
        { 
          
           valor1=10;
           valor2=10;
           abiertas=0; 
        }
        
       
            
        
            
        
    
    
        System.out.println(valor1);
        System.out.println(valor2);
        
  
    }//GEN-LAST:event_btm16ActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
   posicion=0;
   aleatorio=0;
   
   abiertas=0;
   valor1=10;
   valor2=10;
   poscision=0;
   posicion2=0;
   intentos=0;
   cartas=1;
   btm1.setText(String.valueOf(" "));
   btm2.setText(String.valueOf(" "));
   btm3.setText(String.valueOf(" "));
   btm4.setText(String.valueOf(" "));
   btm5.setText(String.valueOf(" "));
   btm6.setText(String.valueOf(" "));
   btm7.setText(String.valueOf(" "));
   btm8.setText(String.valueOf(" "));
   btm9.setText(String.valueOf(" "));
   btm10.setText(String.valueOf(" "));
   btm11.setText(String.valueOf(" "));
   btm12.setText(String.valueOf(" "));
   btm13.setText(String.valueOf(" "));
   btm14.setText(String.valueOf(" "));
   btm15.setText(String.valueOf(" "));
   btm16.setText(String.valueOf(" "));
   btm1.setEnabled(true);
   btm2.setEnabled(true);
   btm3.setEnabled(true);
   btm4.setEnabled(true);
   btm5.setEnabled(true);
   btm6.setEnabled(true);
   btm7.setEnabled(true);
   btm8.setEnabled(true);
   btm9.setEnabled(true);
   btm10.setEnabled(true);
   btm11.setEnabled(true);
   btm12.setEnabled(true);
   btm13.setEnabled(true);
   btm14.setEnabled(true);
   btm15.setEnabled(true);
   btm16.setEnabled(true);
   while (contador <=16)
   {
       numeros[contador]=0;
       contador+=1;
   }
   contador=0;
   

        while (contador<=14)
        {
            aleatorio=(int)(Math.random()*15 );
            if (numeros[aleatorio]==0)
            {
                numeros[aleatorio]=cartas;
                contador+=1;
                cartas+=1;
                if (cartas>7)
                {
                    cartas=0;
                }
            }
            
        }
            
      
                    

    
   
    }//GEN-LAST:event_btnResetActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFmemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFmemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFmemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFmemoria.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFmemoria().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btm1;
    private javax.swing.JButton btm10;
    private javax.swing.JButton btm11;
    private javax.swing.JButton btm12;
    private javax.swing.JButton btm13;
    private javax.swing.JButton btm14;
    private javax.swing.JButton btm15;
    private javax.swing.JButton btm16;
    private javax.swing.JButton btm2;
    private javax.swing.JButton btm3;
    private javax.swing.JButton btm4;
    private javax.swing.JButton btm5;
    private javax.swing.JButton btm6;
    private javax.swing.JButton btm7;
    private javax.swing.JButton btm8;
    private javax.swing.JButton btm9;
    private javax.swing.JButton btnReset;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel lblIntentos;
    // End of variables declaration//GEN-END:variables
}
