/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package enunciados;

/**
 *
 * @author JoseDaniel
 */
public class FrmEnunciados extends javax.swing.JFrame {

    int aleatorio1;
    int aleatorio2;
    int aleatorio3;
    int aleatorio4;
    int aleatorio5;
    int aleatorio6;
    String palabra1;
    String palabra2;
    String palabra3;
    String palabra4;
    String palabra5;
    String palabra6;
    String articulo[] = {"el", "un", "algun", "ningun"};
    String sustantivo[] = {"niño", "niña", "perro", "ciudad", "auto"};
    String verbo[] = {"manejo", "salto", "corrió", "camino", "omitió"};
    String preposicion[] = {"a", "desde", "encima de", "debajo de", "sobre"};

    public FrmEnunciados() {
        initComponents();

        aleatorio1 = (int) (Math.random() * 4);
        System.out.println(aleatorio1);
        palabra1 = Character.toString(articulo[aleatorio1].charAt(0)).toUpperCase() + articulo[aleatorio1].substring(1) + " ";
        lblpalabra1.setText(String.valueOf(palabra1));
        
        aleatorio2 = (int) (Math.random() * 5);
        System.out.println(aleatorio2);
        palabra2 = sustantivo[aleatorio2] + " ";
        lblpalabra2.setText(String.valueOf(palabra2));
        
        aleatorio3 = (int) (Math.random() * 5);
        System.out.println(aleatorio3);
        palabra3 = verbo[aleatorio3] + " ";
        lblpalabra3.setText(String.valueOf(palabra3));
        
        aleatorio4 = (int) (Math.random() * 5);
        System.out.println(aleatorio4);
        palabra4 = preposicion[aleatorio4] + " ";
        lblpalabra4.setText(String.valueOf(palabra4));
        
        
        
        
        aleatorio5 = (int) (Math.random() * 4);      
        System.out.println(aleatorio5);
        palabra5 = articulo[aleatorio5] + " ";
        lblpalabra5.setText(String.valueOf(palabra5));
        
        
        
        
        aleatorio6 = (int) (Math.random() * 5);
        System.out.println(aleatorio6);
        palabra6 = sustantivo[aleatorio6] + ".";
        lblpalabra6.setText(String.valueOf(palabra6));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblpalabra1 = new javax.swing.JLabel();
        lblpalabra2 = new javax.swing.JLabel();
        lblpalabra3 = new javax.swing.JLabel();
        lblpalabra4 = new javax.swing.JLabel();
        btmnuevaoracion = new javax.swing.JButton();
        lblpalabra5 = new javax.swing.JLabel();
        lblpalabra6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 255, 102));

        lblpalabra1.setForeground(new java.awt.Color(51, 255, 255));

        lblpalabra2.setForeground(new java.awt.Color(0, 0, 255));

        lblpalabra3.setForeground(new java.awt.Color(204, 51, 255));

        lblpalabra4.setForeground(new java.awt.Color(255, 0, 51));

        btmnuevaoracion.setText("Oracion");
        btmnuevaoracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btmnuevaoracionActionPerformed(evt);
            }
        });

        lblpalabra5.setForeground(new java.awt.Color(255, 153, 0));

        lblpalabra6.setForeground(new java.awt.Color(0, 255, 0));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btmnuevaoracion)
                    .addComponent(lblpalabra1, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpalabra2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpalabra3, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpalabra4, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpalabra5, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblpalabra6, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(lblpalabra6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(116, 116, 116)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblpalabra1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblpalabra2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblpalabra3, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblpalabra4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(lblpalabra5, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 71, Short.MAX_VALUE)
                .addComponent(btmnuevaoracion)
                .addGap(61, 61, 61))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btmnuevaoracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btmnuevaoracionActionPerformed
        aleatorio1 = (int) (Math.random() * 4);
        System.out.println(aleatorio1);
        palabra1 = Character.toString(articulo[aleatorio1].charAt(0)).toUpperCase() + articulo[aleatorio1].substring(1) + " ";
        lblpalabra1.setText(String.valueOf(palabra1));
        
        aleatorio2 = (int) (Math.random() * 5);
        System.out.println(aleatorio2);
        palabra2 = sustantivo[aleatorio2] + " ";
        lblpalabra2.setText(String.valueOf(palabra2));
        
        aleatorio3 = (int) (Math.random() * 5);
        System.out.println(aleatorio3);
        palabra3 = verbo[aleatorio3] + " ";
        lblpalabra3.setText(String.valueOf(palabra3));
        
        aleatorio4 = (int) (Math.random() * 5);
        System.out.println(aleatorio4);
        palabra4 = preposicion[aleatorio4] + " ";
        lblpalabra4.setText(String.valueOf(palabra4));
        
        
        
        
        aleatorio5 = (int) (Math.random() * 4);      
        System.out.println(aleatorio5);
        palabra5 = articulo[aleatorio5] + " ";
        lblpalabra5.setText(String.valueOf(palabra5));
        
        
        
        
        aleatorio6 = (int) (Math.random() * 5);
        System.out.println(aleatorio6);
        palabra6 = sustantivo[aleatorio6] + ".";
        lblpalabra6.setText(String.valueOf(palabra6));
    }//GEN-LAST:event_btmnuevaoracionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmEnunciados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmEnunciados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmEnunciados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmEnunciados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmEnunciados().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btmnuevaoracion;
    private javax.swing.JLabel lblpalabra1;
    private javax.swing.JLabel lblpalabra2;
    private javax.swing.JLabel lblpalabra3;
    private javax.swing.JLabel lblpalabra4;
    private javax.swing.JLabel lblpalabra5;
    private javax.swing.JLabel lblpalabra6;
    // End of variables declaration//GEN-END:variables
}
