/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package piedra.papel.o.tijera;
    
import javax.swing.JOptionPane;

/**
 *
 * @author 59399
 */
public class PiedraPapelTijera extends javax.swing.JFrame {
int aleatorio;
int piedra=1;
int papel=2;
int tijera=3;
int spock=4;
int lagarto=5;
int ganadas=0;
int perdidas=-0;
int total=0;
    /**
     * Creates new form PiedraPapelTijera
     */
    public PiedraPapelTijera() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SPOCK = new javax.swing.JButton();
        TIJERA = new javax.swing.JButton();
        LAGARTO = new javax.swing.JButton();
        PAPEL = new javax.swing.JButton();
        PIEDRA = new javax.swing.JButton();
        REPETIR = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        SPOCK.setBackground(new java.awt.Color(0, 0, 204));
        SPOCK.setText("SPOCK");
        SPOCK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SPOCKActionPerformed(evt);
            }
        });
        getContentPane().add(SPOCK);
        SPOCK.setBounds(300, 100, 90, 30);

        TIJERA.setBackground(new java.awt.Color(51, 255, 51));
        TIJERA.setText("TIJERA");
        TIJERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TIJERAActionPerformed(evt);
            }
        });
        getContentPane().add(TIJERA);
        TIJERA.setBounds(110, 130, 100, 35);

        LAGARTO.setBackground(new java.awt.Color(153, 0, 153));
        LAGARTO.setText("LAGARTO");
        LAGARTO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LAGARTOActionPerformed(evt);
            }
        });
        getContentPane().add(LAGARTO);
        LAGARTO.setBounds(480, 140, 100, 30);

        PAPEL.setBackground(new java.awt.Color(255, 0, 51));
        PAPEL.setText("PAPEL");
        PAPEL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PAPELActionPerformed(evt);
            }
        });
        getContentPane().add(PAPEL);
        PAPEL.setBounds(190, 480, 90, 30);

        PIEDRA.setBackground(new java.awt.Color(0, 204, 204));
        PIEDRA.setText("PIEDRA");
        PIEDRA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PIEDRAActionPerformed(evt);
            }
        });
        getContentPane().add(PIEDRA);
        PIEDRA.setBounds(400, 480, 100, 30);

        REPETIR.setBackground(new java.awt.Color(229, 252, 5));
        REPETIR.setText("TRY AGAIN");
        REPETIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                REPETIRActionPerformed(evt);
            }
        });
        getContentPane().add(REPETIR);
        REPETIR.setBounds(460, 40, 120, 23);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/piedra/papel/o/tijera/general.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(110, 20, 533, 500);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TIJERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TIJERAActionPerformed
    total=total+1;
    if (aleatorio == lagarto) 
        { 
             JOptionPane.showMessageDialog(null," GANASTE! tijera gana lagarto");
             ganadas=ganadas+1;
             
        }
    else if(aleatorio==papel)
        {
             JOptionPane.showMessageDialog(null," GANASTE! tijera gana PAPEL");
             ganadas=ganadas+1;
        }
    else if(aleatorio == piedra)
        {   
             JOptionPane.showMessageDialog(null,"PIERDES ! piedra gana tijera ");
             perdidas=perdidas+1;
        }
    else if(aleatorio == spock)
        {
             JOptionPane.showMessageDialog(null,"PIERDES! spock gana tijera "); 
             perdidas=perdidas+1;
        }
    else
        {
             JOptionPane.showMessageDialog(null,"EMPATE ");
        }
    }//GEN-LAST:event_TIJERAActionPerformed

    private void SPOCKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SPOCKActionPerformed
    total=total+1;
    if (aleatorio == piedra ) 
        { 
             JOptionPane.showMessageDialog(null," GANASTE!SPOCK GANA A PIEDRA ");
             ganadas=ganadas+1;
        }
    else if(aleatorio== tijera)
        {
             JOptionPane.showMessageDialog(null," GANASTE! SPOCK GANA A TIJERA ");
             ganadas=ganadas+1;
        }
    else if(aleatorio == lagarto )
        {   
             JOptionPane.showMessageDialog(null,"PIERDES !  LAGARTO GANA A SPOCK");
             perdidas=perdidas+1;
             
        }
    else if (aleatorio == papel)
        {
            JOptionPane.showMessageDialog(null,"PIERDES ! PAPEL GANA A SPOCK");
            perdidas=perdidas+1;
        }
    else 
        {
            JOptionPane.showMessageDialog(null,"EMPATE!  "); 
        }
    }//GEN-LAST:event_SPOCKActionPerformed

    private void REPETIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_REPETIRActionPerformed
    aleatorio=(int)(Math.random()*5+1);
    System.out.print(aleatorio);
    
    
    }//GEN-LAST:event_REPETIRActionPerformed

    private void LAGARTOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LAGARTOActionPerformed
    total=total+1;
    if (aleatorio == spock ) 
        { 
             JOptionPane.showMessageDialog(null," GANASTE! LAGARTO GANA SPOCK ");
             ganadas=ganadas+1;
        }
    else if(aleatorio== papel)
        {
             JOptionPane.showMessageDialog(null," GANASTE! LAGARTO GANA PAPEL ");
             ganadas=ganadas+1;
        }
    else if(aleatorio == piedra )
        {   
             JOptionPane.showMessageDialog(null,"PIERDES ! PIEDRA GANA A LAGARTO ");
             perdidas=perdidas+1;
        }
    else if (aleatorio == tijera )
        {
            JOptionPane.showMessageDialog(null,"PIERDES ! TIJERA GANA A LAGARTO");
            perdidas=perdidas+1;
        }
    else 
        {
            JOptionPane.showMessageDialog(null,"EMPATE!  "); 
        }   // TODO add your handling code here:
    }//GEN-LAST:event_LAGARTOActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
aleatorio=(int)(Math.random()*5+1);
    System.out.print(aleatorio);   
    
// TODO add your handling code here:
    }//GEN-LAST:event_formWindowOpened

    private void PAPELActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PAPELActionPerformed
    total=total+1;
    if (aleatorio == spock ) 
        { 
             JOptionPane.showMessageDialog(null," GANASTE! PAPEL GANA SPOCK ");
             ganadas=ganadas+1;
        }
    else if(aleatorio== piedra)
        {
             JOptionPane.showMessageDialog(null," GANASTE! PAPEL GANA PIEDRA ");
             ganadas=ganadas+1;
        }
    else if(aleatorio == lagarto )
        {   
             JOptionPane.showMessageDialog(null,"PIERDES ! LAGARTO GANA PAPEL ");
             perdidas=perdidas+1;
        }
    else if (aleatorio == tijera )
        {
            JOptionPane.showMessageDialog(null,"PIERDES ! TIJERA GANA A PAPEL");
            perdidas=perdidas+1;
        }
    else 
        {
            JOptionPane.showMessageDialog(null,"EMPATE!  "); 
        }
    }//GEN-LAST:event_PAPELActionPerformed

    private void PIEDRAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PIEDRAActionPerformed
    total=total+1;
    if (aleatorio == tijera ) 
        { 
             JOptionPane.showMessageDialog(null," GANASTE! PIEDRA GANA TIJERA ");
             ganadas=ganadas+1;
        }
    else if(aleatorio== lagarto)
        {
             JOptionPane.showMessageDialog(null," GANASTE! PIEDRA GANA LAGARTO ");
             ganadas=ganadas+1;
        }
    else if(aleatorio == spock )
        {   
             JOptionPane.showMessageDialog(null,"PIERDES ! SPOCK GANA PIEDRA ");
             perdidas=perdidas+1;
        }
    else if (aleatorio == papel )
        {
            JOptionPane.showMessageDialog(null,"PIERDES ! PAPEL GANA A PIEDRA");
            perdidas=perdidas+1;
        }
    else 
        {
            JOptionPane.showMessageDialog(null,"EMPATE!  "); 
        }    // TODO add your handling code here:
    }//GEN-LAST:event_PIEDRAActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PiedraPapelTijera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PiedraPapelTijera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PiedraPapelTijera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PiedraPapelTijera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PiedraPapelTijera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton LAGARTO;
    private javax.swing.JButton PAPEL;
    private javax.swing.JButton PIEDRA;
    private javax.swing.JButton REPETIR;
    private javax.swing.JButton SPOCK;
    private javax.swing.JButton TIJERA;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
